### ISSUE TITLE
Create my own dataset with Shapenet

### ISSUE THREAD

**Issue by hetolin** [UM-ARM-Lab/mps_shape_completion#12]
Hi, thank you for sharing your code.It seems useful. I want to use this code to train my own dataset.But now I only have the depth map and the ground truth meshes.I wonder how could I create the dataset as you described.
I am going to change the depth map into point cloud, and then sample the mesh into point cloud, then what should I do to align then in the format of binvox?

**Comment by bsaund** [comment]
Hello,
If I understand your question correctly, your dataset consists of a depth map as input, and mesh as "ground truth", but you do not know the alignment, and you are asking how to get this alignment. This is a general question and not specific to this repo. I'd suggest:
1) Generate the depth map in the same frame as the mesh
2) If that is not possible, you can use ICP or some other point<->mesh fitting method to align them

Once you have a point cloud you can generate a voxel grid and then write a binvox. Examing `binvox_rw` in the `mps_shape_completion` folder for the details.

**Comment by hetolin** [comment]
Thank you very much for your reply.I will have a try as you said.
